[project]
name = "first-proj"
version = "0.1.0"
description = ""
authors = [
    { name = "dae22", email = "dae-22@mail.ru" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=5.2.5,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
ruff = "^0.12.8"
pre-commit = "^4.3.0"

[tool.poetry.scripts]
lint = "pre-commit run --all-files"

[tool.ruff]
select = [
    "E",
    "F",
    "I",
    "UP",
    "C90",
    "B",
    "Q",
    "E501"
]

line-length = 88

fix = true

[tool.ruff.isort]
known-first-party = ["first-proj"]
