# Generated by Django 5.2.5 on 2025-08-18 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="apt_id",
            new_name="apartment",
        ),
    ]
