# Generated by Django 5.2.5 on 2025-08-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0001_initial"),
        ("booking", "0002_rename_apt_id_booking_apartment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="apartments.apartments",
            ),
        ),
    ]
