# Generated by Django 5.2.5 on 2025-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_booking_apartment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["start"]},
        ),
    ]
