# Generated by Django 5.2.5 on 2025-08-29 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["start_date"]},
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="end",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="start",
            new_name="start_date",
        ),
    ]
